

services:
  project-shedule-django:
    container_name: project-shedule-django
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/project-shedule-django
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - .env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env
