# Generated by Django 5.0.4 on 2024-04-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cretead_date',
            new_name='created_date',
        ),
    ]
